pipeline {
    agent any

    tools {
        jdk 'jdk11'
        maven 'maven3'
    }

    environment {
        SCANNER_HOME = tool 'sonar-scanner'
    }

    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'main', changelog: false, poll: false, url: 'https://github.com/gabrielabalbuena/CI-CD-Pipeline.git'
            }
        }

        stage('Compile') {
            steps {
                sh "mvn clean compile"
            }
        }

        stage('Sonarqube Analysis'){
            steps{
                sh ''' 
                $SCANNER_HOME/bin/sonar-scanner \
                -Dsonar.url=http://sonarqube:9000/ \
                -Dsonar.login=squ_760725565e26189d33b4ea1c035cc963556a5b35 \
                -Dsonar.projectName=SpringBootHelloWorld \
                -Dsonar.java.binaries=. \
                -Dsonar.projectKey=SpringBootHelloWorld 
                '''
            }
        }

        stage('OWASP SCAN') {
            steps {
                dependencyCheck additionalArguments: ' --scan ./', odcInstallation: 'DP'
                dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
            }
        }
    }
}
