pipeline{
    agent any

    stages{
        stage('Docker Deploy To Container'){
            steps{
                script{
                   withDockerRegistry(credentialsId: 'c9f8cfae-4d4f-4c24-8b01-105751d317af', toolName: 'docker') {
                        sh "docker run -d --name spring-hello-world -p 8070:8070 gbalbuena25/sp-hello-world:latest"
                    } 
                }
            }
        }
    }
}